server:
  port: 9528

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery: #发现
        locator:  # 定位球
          enabled: true #开启从注册中心动态创建路由的功能，利用为服务名进行路由
      routes: # 路由
        - id: payment_routh #payment_route 路由的ID 没有固定规则 要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #eureka上的服务名
          predicates:
            - Path=/payment/get/**  #断言 路径匹配的进行路由
        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE #eureka上的服务名
          predicates:
            - Path=/payment/lb/** # 断言 路径匹配的进行路由
            - After=2020-04-01T16:04:26.470+08:00[Asia/Shanghai] #这个时间传通过ZoneDateTime 获取
            #- Cookie=username,lyq
              #[After]  时间控制 在指定的时间后可以访问
              #[Before] 指定时间前可以访问呢
              #[Between]  在直接定的时间段内可以访问 两个时间 开始时间 +"," +结束时间
              #[Cookie] Cookie 带cookie的可以访问
              #[Header] 符合的请求头
              #[Host]
              #[Method]
              #[Path]  uri控制 符合的uri可以访问
              #[Query]
              #[ReadBodyPredicateFactory]
              #[RemoteAddr]
              #[Weight]
              #[CloudFoundryRouteService]
eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: cloud-gateway-service
  client:
    register-with-eureka: true #是否注册到eureka
    fetch-registry: true #是否刷新
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka