server:
  port: 7001

# eureka 配置
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: true  #false 表示不向注册中心注册自己
    fetch-registry: false # 表示自己就时注册中心 不需要检索服务
    service-url:
      #设置erueka 服务交互的地址
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/